# Generated by Django 5.0.3 on 2024-04-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_content_phone_email_rename_title_phone_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
