# Generated by Django 5.0.3 on 2024-04-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_phone_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['name']},
        ),
    ]
