# Generated by Django 5.0.6 on 2024-05-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_category_comment_like_post_like_postcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default='True'),
        ),
    ]
