# Generated by Django 5.0.6 on 2024-06-21 10:21

import BlogApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_like_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=BlogApp.models.upload_filepath),
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, upload_to=BlogApp.models.upload_filepath),
        ),
    ]
