# Generated by Django 5.0.6 on 2024-06-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_post_image_post_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='media',
            new_name='video',
        ),
    ]
